name: Setup Build Env
description: Setup build environment with go and protoc

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.23"
