name: pull-request

on:
  pull_request:
    branches: ["main"]

permissions: {}
        
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint commits
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        uses: ./.github/actions/lint-commit

  build:
    needs:
      - commitlint
    uses: ./.github/workflows/test.yaml